"""Changed typo in Sales table

Revision ID: 0117b3fc5500
Revises: a7df68ffd112
Create Date: 2024-02-03 15:20:09.108436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0117b3fc5500'
down_revision = 'a7df68ffd112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.drop_column('qunatity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qunatity', sa.INTEGER(), nullable=True))
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
